apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.17.200.100-172.17.200.125
 # Add this in the middle of the chapter - Adding mutiple IP pools     
   # - name: subnet-201
   #   protocol: layer2
   #   addresses:
   #   - 172.17.201.100-172.17.201.125
